task/urls.py
from django.urls import path
from .views import *

urlpatterns = [
   path('', signin, name='signin'),
   path('logout/', signout, name='logout'),
   path('resistration/', registration, name='registration'),
   path('index/', index , name='index'),
   path('addCategory/', addCategory, name='addCategory'),
   path('addTask/', addTask, name='addTask'),
   path('<int:pk>/taskCategorie/', taskCategorie, name='task_categorie'),
   path('<int:id>/achevetask/', task_acheve, name='acheve_task')
]

todolist/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('task.urls')),
    path('admin/', admin.site.urls),
]

task/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class Categorie(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, validators=[MinLengthValidator(3)])
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Task(models.Model):
    priority_choice = [
        ('Basse', 'Basse'),
        ('Moyenne', 'Moyenne'),
        ('Haute', 'Haute'),
        ('Maximale', 'Maximale'),
    ]
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    categorie = models.ForeignKey(Categorie, on_delete=models.CASCADE, db_index=True)
    title = models.CharField(max_length=100, validators=[MinLengthValidator(3)])
    description = models.TextField(blank=True, null=True)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    priority = models.CharField(max_length=10, choices=priority_choice, default='Basse')
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta:
        indexes = [
            models.Index(fields=['categorie', 'end_date', 'start_date', 'priority'])
        ]

task/forms.py
from django import forms
from django.contrib.auth.models import User
from task.models import Categorie, Task

class RegistrationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')

class SiginForm(forms.Form):
    username = forms.CharField(max_length=50, min_length=3, required=True)
    password = forms.CharField(max_length=50, min_length=3, required=True)


class CategorieForm(forms.ModelForm):
    class Meta:
        model = Categorie
        fields = ('name', )
        widjets = {
            'name': forms.TextInput(attrs={'class': 'form-control bg-dark text-white border-secondary'}),
        }

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('categorie', 'title', 'description', 'start_date', 'end_date', 'priority')
        widgets = {
            'categorie': forms.Select(attrs={'class': 'form-control bg-dark text-white border-secondary'}),
            'title': forms.TextInput(attrs={'class': 'form-control bg-dark text-white border-secondary'}),
            'description': forms.Textarea(attrs={'class': 'form-control bg-dark text-white border-secondary', 'rows': 3}),
            'start_date': forms.DateTimeInput(format='%Y-%m-%dT%H:%M',attrs={'type': 'date', 'class': 'form-control bg-dark text-white border-secondary','type': 'datetime-local'}),
            'end_date': forms.DateTimeInput(format='%Y-%m-%dT%H:%M',attrs={'type': 'date', 'class': 'form-control bg-dark text-white border-secondary','type': 'datetime-local'}),
            'priority': forms.Select(attrs={'class': 'form-control bg-dark text-white border-secondary'}),
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['categorie'].empty_label = "Cliquez pour choisir"
        

task/views.py
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.contrib import messages
from task.forms import CategorieForm, RegistrationForm, SiginForm, TaskForm
from task.models import Categorie, Task
from django.utils import timezone

# Create your views here.
def signin (request):
    if request.method == 'POST':
        form = SiginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse('index'))
            else:
                messages.error(request, "L'utilisateur saisi n'existe pas")
                return redirect(reverse('signin'))
        else:
            print(form.errors)
            return redirect(reverse('signin'))
    else:
        form = SiginForm()
    return render(request, 'signin.html', {'form': form})

def signout(request):
    logout(request)
    return redirect(reverse('signin'))

def registration (request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            user = User.objects.create_user(
                username=cleaned_data.get('username'),
                email=cleaned_data.get('email'),
                password=cleaned_data.get('password'),
                last_name=cleaned_data.get('last_name'),
                first_name=cleaned_data.get('first_name')
            )
            user.save()
            return redirect(reverse('signin'))
        else :
            print(form.errors)
            return redirect(reverse('registration'))
    else:
        form = RegistrationForm()
     
    return render(request, 'registration.html', {'form': form})

def trie(request, tasks):
    filter_date = request.GET.get('date')
    priority_task = request.GET.get('priority')
    status_task = request.GET.get('status')
    today = timezone.now().date()

    if filter_date:
        if filter_date == 'today':
            tasks = tasks.filter(start_date__lte=today, end_date__gte=today)
        elif filter_date == 'futur':
            tasks = tasks.filter(start_date__gt=today)
        elif filter_date == 'passe':
            tasks = tasks.filter(end_date__lt=today)
    
    if priority_task:
        tasks = tasks.filter(priority__iexact=priority_task.capitalize())

    if status_task:
        if status_task == 'termine':
            tasks = tasks.filter(status=True)
        elif status_task == 'nontermine':
            tasks = tasks.filter(status=False)

    return tasks

def taskCategorie(request, pk):
    categories = Categorie.objects.all()
    categorie = Categorie.objects.get(pk=pk)
    tasks = Task.objects.filter(categorie=categorie).order_by('-start_date')  

    tasks = trie(request, tasks)
    context = {
        'tasks': tasks,
        'categories': categories,
        'today': timezone.now().date(),
    }
    
    return render(request, 'index.html', context)   

@login_required(login_url='/signin/')
def index(request):
    categories = Categorie.objects.all()
    formCategory = CategorieForm()
    formTask = TaskForm()
    tasks = Task.objects.all()

    tasks = trie(request, tasks)
    context = {
        'categories': categories,
        'formCategory': formCategory,
        'formTask': formTask, 
        'tasks': tasks,
        'today': timezone.now().date
    }
        
    return render(request, 'index.html', context)


def addCategory(request):
    if request.method == 'POST':
        formCategory = CategorieForm(request.POST)
        if formCategory.is_valid():
            formCategory.save()
            messages.success(request, 'Categorie bien enregistrer')
            return redirect(reverse('index'))
        else :
            print(formCategory.errors)
            messages.error(request, 'Categorie non enregistrer')
            return redirect(reverse('index'))
    else :
        formCategory = CategorieForm()
        context = {'formCategory': formCategory}
        
    return render(request, 'addCategory.html', context) 

def addTask(request):
    if request.method == 'POST':
        formTask = TaskForm(request.POST)
        if formTask.is_valid():
            formTask.save()
            messages.success(request, 'Tâche bien enregistrer')
            return redirect(reverse('index'))
        else :
            print(formTask.errors)
            messages.error(request, 'Tâche non enregistrer')
            return redirect(reverse('index'))
    else :
        formTask = TaskForm()
        context = {'formTask': formTask}
        
    return render(request, 'addTask.html', context)


def task_acheve(request, id):
    task = Task.objects.get(id=id)
    task.status = True
    task.save()
    messages.success(request, 'Tâche terminé')
    return redirect(reverse('index'))

task/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My to do list</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <style>
        .categorie {
            font-size: large;
        }

        .colCategorie {
            background-color: #383e41;
            height: 80vh;
            border-radius: 5px;
        }

        label {
            color: white !important;
        }
    </style>
</head>

<body class='container bg-dark'>
    <div class="m-5 mt-5 border-light">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} me-5">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        <div class="row">
            <h4 class="text-light">1000<span class="text-success">TechLeaders</span></h4>
            <div class="col-2 colCategorie">
                <button class="form-control fw-bold my-3" type="button" data-bs-toggle="modal"
                    data-bs-target="#exampleModal">+
                    Ajouter</button>
                <a href="{% url "index" %}" class="text-decoration-none bg-dark fw-bold text-white">
                    <div class="row d-flex categorie py-2 align-item-between">
                        <div class="col-7 text-start">Tout</div>
                        <div class="col-5 text-end">{{ categories.count }}</div>
                    </div>
                </a>
                {% for categorie in categories %}
                <a href="{% url "task_categorie" categorie.pk %}" class="text-decoration-none bg-dark fw-bold text-white">
                    <div class="row d-flex categorie py-2 align-item-between">
                        <div class="col-7 text-start">{{ categorie.name|title }}</div>
                        <div class="col-5 text-end">{{ categorie.task_set.count }}</div>
                    </div>
                </a>
                {% endfor %}
            </div>
            <div class="col-9 ms-3 colCategorie">
                <div class="row mt-2 justify-content-between d-flex">
                    <div class="col-9"><h2 class="text-light">Bonjour, Ibrahima</h2></div>
                    <div class="col  d-flex align-items-end">
                        <form action="{% url 'logout' %}" method="post">
                            {% csrf_token %}
                            <button type='submit' class="btn btn-outline-light">Se deconnecter</button>
                        </form>
                        
                    </div>
                </div>
                
                <h4 class="text-light">Aujourd'hui c'est : {{ today|date:'l d F Y' }}</h4>

                <div class="row container d-flex align-items-center my-2">
                    <div class="row d-flex align-items-end mb-3 justify-content-end">
                        <form method="get" class="row">
                            <div class="col-3">
                                <select name="priority" class="form-select btn-outline-dark" onchange="this.form.submit()">
                                    <option value="">Filtrer par priorite</option>
                                    <option value="basse" {% if request.GET.priority == 'basse' %}selected{% endif %}>Basse</option>
                                    <option value="moyenne" {% if request.GET.priority == 'moyenne' %}selected{% endif %}>Moyenne</option>
                                    <option value="haute" {% if request.GET.priority == 'haute' %}selected{% endif %}>Haute</option>
                                    <option value="maximale" {% if request.GET.priority == 'maximale' %}selected{% endif %}>Maximale</option>
                                </select>
                            </div>
                            <div class="col-3">
                                <select name="date" class="form-select btn-outline-dark" onchange="this.form.submit()">
                                    <option value="">Filtrer par moment</option>
                                    <option value="today" {% if request.GET.date == 'today' %}selected{% endif %}>Aujourd'hui</option>
                                    <option value="futur" {% if request.GET.date == 'futur' %}selected{% endif %}>À venir</option>
                                    <option value="passe" {% if request.GET.date == 'passe' %}selected{% endif %}>Passé</option>
                                </select>
                            </div>
                            <div class="col-3">
                                <select name="status" class="form-select btn-outline-dark" onchange="this.form.submit()">
                                    <option value="">Filtrer par status</option>
                                    <option value="termine" {% if request.GET.status == 'termine' %}selected{% endif %}>Terminé</option>
                                    <option value="nontermine" {% if request.GET.status == 'nontermine' %}selected{% endif %}>Non Terminé</option>
                                </select>
                            </div>
                        </form>
                    </div>

                    <ul class="list-group">
                        {% for task in tasks %}
                        <li class="list-group-item d-flex text-light bg-dark justify-content-between align-items-center">
                            <div class="text-start">
                                <input type="checkbox" {% if task.status %} checked {% endif %} disabled>
                                {{ task.title }} <small class="text-secondary">({{ task.categorie.name }})</small>
                            </div>
                            {{ task.description }}
                            <span class="text-muted">{{ task.start_date|date:"H:i" }}-{{ task.end_date|date:"H:i" }}
                                {% if not task.status %}
                                <form action="{% url "acheve_task" task.id %}" method="post" style="display:inline;">
                                    {% csrf_token %}
                                    <button type="submit" class="btn border-secondary btn-outline-dark text-white">Achevé</button>
                                </form>
                                {% endif %}
                            </span>
                        </li>
                        {% endfor %}
                    </ul>
                </div>

                <button type="button" class="btn btn-outline-light" data-bs-toggle="modal" data-bs-target="#addTask">Ajouter une tâche</button>
            </div>
        </div>
    </div>

    {% comment %} modal pour ajouter une categorie {% endcomment %}
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content container bg-dark">
                <h1 class="modal-title fs-5 text-light" id="exampleModalLabel">Ajouter une categorie</h1>
                <form action="{% url 'addCategory' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group mb-3">
                        <label for="name" class="form-label text-light">Nom de la categorie:</label>
                        <input type="text" class="form-control" id="name" name="name">
                    </div>
                    <button type="submit" class="btn btn-outline-light">Enregistrer</button>
                    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Fermer</button>
                </form>
            </div>
        </div>
    </div>

    {% comment %} modal pour ajouter une tâche {% endcomment %}
    <div class="modal fade" id="addTask" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content bg-dark">
                <div class="modal-header">
                    <h1 class="modal-title fs-5 text-light" id="exampleModalLabel">Ajouter une tâche</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'addTask' %}" method="post">
                        {% csrf_token %}
                        {{ formTask.as_p }}
                        <button type="submit" class="btn btn-outline-light">Enregistrer</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

task/templates/registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inscription</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        

        .form-signup {
            max-width: 400px;
            margin: auto;
            padding: 15px;
            background-color: #383e41;
            border-radius: 10px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);
        }

        .form-signup h1 {
            color: white;
            text-align: center;
            margin-bottom: 20px;
        }

        .form-signup label {
            color: white; /* Couleur gris clair pour les labels */
        }

        .form-signup .form-control {
            background-color: #383e41;
            color: white;
            border: 1px solid #ced4da;
        }

        .form-signup .form-control:focus {
            background-color: #495057;
            color: white;
            border-color: #adb5bd;
            box-shadow: none;
        }

        .form-signup .btn {
            margin-top: 15px;
        }

        .form-signup .text-center a {
            color: #0d6efd;
            text-decoration: none;
        }

        .form-signup .text-center a:hover {
            text-decoration: underline;
        }
    </style>
</head>

<body class='bg-dark'>
    <div class="container">
        <form class="form-signup mt-5" action="" method="POST">
            {% csrf_token %}
            <h1>Inscription</h1>
            <div class="mb-3">
                <label for="first_name" class="form-label">Prénom</label>
                <input type="text" class="form-control" id="first_name" name="first_name">
            </div>
            <div class="mb-3">
                <label for="last_name" class="form-label">Nom</label>
                <input type="text" class="form-control" id="last_name" name="last_name">
            </div>
            <div class="mb-3">
                <label for="username" class="form-label">Nom d'utilisateur</label>
                <input type="text" class="form-control" id="username" name="username" required>
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="email" class="form-control" id="email" name="email">
                {{form.email.errors}}
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Mot de passe</label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <button type="submit" class="btn btn-outline-primary">S'inscrire</button>
            <button type="reset" class="btn btn-outline-secondary">Annuler</button>
            <div class="text-center mt-3">
                <p class="text-light">Vous avez déjà un compte? <a href="/login">Connectez-vous ici</a>.</p>
            </div>
        </form>
    </div>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
</body>

</html>

task/templates/signin.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <title>Connexion</title>

    <!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> 
    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
  </head>
  <body class="text-center bg-dark">
    
<main class="form-signin">
  {% if messages %}
    {% for message in messages  %}
      <div class="alert-danger text-danger">{{message}}</div>
    {% endfor %}
  {% endif %}
  <form method="POST">
    {% csrf_token %}
    <h1 class="text-light">1000<span class="text-success">TechLeaders</span></h1>
    <h1 class="h3 mb-3 fw-normal text-light">Se Connecter</h1>
    
    <div class="">
      <label class="text-light">Nom d'utilisateur</label>
      <input type="text" class="form-control bg-dark text-light border-secondary" name="username" >
      
    </div>
    <div class=" mt-3">
      <label for="" class='text-light'>Mot de passe</label>
      <input type="password" class="form-control bg-dark text-light border-secondary" name="password" id="" placeholder="Password">
      
    </div>

    <div class="checkbox mb-3">
      <label class='text-light'>
        J'ai pas de compte. <a href="{% url 'registration' %}" class="text-warning">M'inscrire</a>
      </label>
    </div>
    <button class="w-100 btn btn-lg btn-outline-light" type="submit">Connexion</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2024</p>
  </form>
</main>


    
  </body>
</html>